test
gryz1/group22 pull request #1
Opened 2022-01-14 19:47 UTC by Maxstr75

test

2022-01-14 19:55 UTC, gryz1 requested changes
изменить маржин

2022-01-15 12:16 UTC, gryz1 requested changes
fix link and ul

2022-01-16 21:07 UTC, gryz1 commented on src/sass/_footer.scss
> +  @media screen and (min-width: 1200px) {
1200 на 1280

2022-01-16 21:16 UTC, gryz1 commented on src/partials/footer.html
> +<section class="footer">
должен быть не <section>  а <footer></footer> , вспомни наше дз, первым идет хедер,секция, а потом футер. У каждого свой тэг

2022-01-16 21:16 UTC, gryz1 commented on src/partials/footer.html
> +</section>
должен быть не <section>  а <footer></footer> , вспомни наше дз, первым идет хедер,секция, а потом футер. У каждого свой тэг

2022-01-16 21:19 UTC, gryz1 reviewed
<footer></footer>

2022-01-16 21:25 UTC, Maxstr75 commented on src/partials/footer.html
> +<section class="footer">
Исправил. Коммит "change fix footer"

2022-01-16 21:49 UTC, gryz1 commented on src/partials/footer.html
> +</section>
nice

2022-01-16 21:50 UTC, gryz1 approved these changes
nice, будем мержить, потмо проверь весь код с ветки main, завтра будем доделывать  контейнер  и подгонять ширина вьюпорта под все паршалы

2022-01-16 21:51 UTC, merged